(function(root){
 'use strict';
 const KEY='mathelio.learning.v1',defaults={calm:false,table:false,blocks:false,steps:false,large:false,simple:false};
 const escape=s=>String(s).replace(/[&<>"']/g,c=>({'&':'&amp;','<':'&lt;','>':'&gt;','"':'&quot;',"'":'&#39;'}[c]));
 const fmt=n=>String(Math.round(n*100)/100).replace('.',',');
 function clean(value){return Object.fromEntries(Object.entries(defaults).map(([k,v])=>[k,typeof value?.[k]==='boolean'?value[k]:v]));}
 let prefs={...defaults};try{prefs=clean(JSON.parse(root.localStorage?.getItem(KEY)||'{}'));}catch{}
 function set(value){prefs=clean({...prefs,...value});try{root.localStorage.setItem(KEY,JSON.stringify(prefs));return true;}catch{return false;}}
 function autoNext(audioPrefs,track){return audioPrefs.autoNext&&(track==='doom'||(!prefs.steps&&!prefs.calm));}
 function configure(config){return {...config,...(prefs.calm&&config.track!=='doom'?{mode:'practice'}:{})};}
 function apply(){if(!root.document)return;for(const key of ['calm','large','simple'])document.body.classList.toggle('learning-'+key,prefs[key]);const n=root.NumberDisplay;if(n)for(const key of ['units','tens','hundreds','thousands'])document.body.style.setProperty('--place-'+key,n.palette[n.prefs[key]][1]);}
 function settingsHtml(){return `<section class="panel learning-settings"><h2>🌱 Apprendre à mon rythme</h2><p>Active seulement les aides qui te sont utiles. Elles restent disponibles sans modifier les calculs.</p>${[['calm','Mode calme','Entraînement sans bonus de vitesse, passage manuel et animations réduites. Le mode secret Doom garde ses règles.'],['table','Tableau de numération','Aligner les chiffres dans les colonnes milliers, centaines, dizaines, unités et décimales.'],['blocks','Matériel à manipuler','Compter des unités, dizaines, centaines et milliers, puis échanger des paquets.'],['steps','Correction par étapes','Découvrir une étape à la fois après la réponse, puis continuer à ton rythme.'],['large','Grands chiffres et boutons','Agrandir les calculs et les touches du clavier de jeu.'],['simple','Écran épuré','Masquer les décorations sur l’accueil et les raccourcis secondaires pendant les calculs.']].map(([k,label,help])=>`<label class="check"><input id="learning-${k}" type="checkbox" ${prefs[k]?'checked':''}> ${label}</label><p class="muted learning-setting-help">${help}</p>`).join('')}<p id="learning-save-status" role="status"></p><p class="muted">Réglages partagés entre les profils de ce navigateur. Les aides de calcul sont désactivées dans Doom.</p></section>`;}
 function bindSettings(container,onChange=()=>{}){for(const key of Object.keys(defaults)){const input=container.querySelector('#learning-'+key);input.onchange=()=>{const saved=set({[key]:input.checked});apply();onChange();container.querySelector('#learning-save-status').textContent=saved?'Réglages enregistrés.':'Réglages actifs pour cette session ; sauvegarde indisponible.';};}}
 function parts(n){const scaled=Math.round(n*100);if(!Number.isFinite(n)||n<0)return [];return String(scaled).split('').map((d,i,a)=>Number(d)*10**(a.length-i-1)/100).filter(v=>v>0);}
 function correction(q){
  if(q.complement)return [{text:`On cherche ce qui manque pour arriver à 20, en partant de ${fmt(q.a)}.`},{text:`20 − ${fmt(q.a)} = ${fmt(q.answer)}.`},{text:`Vérifions : ${fmt(q.a)} + ${fmt(q.answer)} = 20.`}];
  if(q.op==='div')return [{text:`On cherche combien de groupes de ${fmt(q.b)} forment ${fmt(q.a)}.`},{text:`Le nombre recherché est ${fmt(q.answer)}.`},{text:`Vérifions : ${fmt(q.answer)} × ${fmt(q.b)} = ${fmt(q.a)}.`}];
  const ps=parts(q.b);if(!ps.length)return [{text:`${fmt(q.a)} ${q.op==='mul'?'×':q.op==='sub'?'−':'+'} 0 = ${fmt(q.answer)}.`}];
  const steps=[{text:`Décomposons ${fmt(q.b)} : ${ps.map(fmt).join(' + ')}.`}];
  if(q.op==='mul'){let sum=0;for(const p of ps){const value=Math.round(q.a*p*100)/100;sum+=value;steps.push({text:`${fmt(q.a)} × ${fmt(p)} = ${fmt(value)}.`});}steps.push({text:`Additionnons les résultats : ${ps.map(p=>fmt(q.a*p)).join(' + ')} = ${fmt(q.answer)}.`});}
  else {let value=q.a;for(const p of ps){const before=value;value=Math.round((value+(q.op==='sub'?-p:p))*100)/100;steps.push({text:`${fmt(before)} ${q.op==='sub'?'−':'+'} ${fmt(p)} = ${fmt(value)}.`});}steps.push({text:`Donc ${fmt(q.a)} ${q.op==='sub'?'−':'+'} ${fmt(q.b)} = ${fmt(q.answer)}.`});}
  return steps;
 }
 function digits(value){const s=String(value).replace(/\s/g,'').replace('.',',');if(!/^\d{1,6}(?:,\d{1,2})?$/.test(s))return null;const [a,b='']=s.split(',');return [...a.padStart(6,' '),...b.padEnd(2,' ')];}
 function tableHtml(q,input=''){
  const labels=['CM','DM','M','C','D','U','d','c'],keys=['hundreds','tens','thousands','hundreds','tens','units',null,null];
  const values=[['Premier nombre',q.a],[q.complement?'Objectif':'Deuxième nombre',q.complement?20:q.b]];if(digits(input))values.push(['Ta réponse',input]);
  const rows=values.map(([label,value])=>{const ds=digits(value);if(!ds)return '';return `<tr><th scope="row">${escape(label)} : ${escape(fmt(Number(String(value).replace(',','.'))))}</th>${ds.map((d,i)=>`<td class="${i===6?'place-decimal-start':''}" style="color:var(--place-${keys[i]||'decimal'},#1f2937)">${d===' '?'<span class="empty-place" aria-label="Position vide">—</span>':escape(d)}</td>`).join('')}</tr>`;}).join('');
  return `<div class="table-wrap"><table class="place-table"><caption>Tableau de numération · M : milliers, C : centaines, D : dizaines, U : unités ; d : dixièmes, c : centièmes</caption><thead><tr><th scope="col">Nombre</th>${labels.map(l=>`<th scope="col">${l}</th>`).join('')}</tr></thead><tbody>${rows}</tbody></table></div>`;
 }
 function pieces(value){if(!Number.isInteger(value)||value<0||value>9999)throw Error('Choisis un entier entre 0 et 9 999.');const result=[];for(const unit of [1000,100,10,1]){const count=Math.floor(value/unit);value%=unit;for(let i=0;i<count;i++)result.push(unit);}return result;}
 function exchange(list,value,direction){
  if(![10,100,1000].includes(value)||!['split','group'].includes(direction))throw Error('Échange invalide.');const copy=[...list];if(direction==='split'){const i=copy.indexOf(value);if(i<0)throw Error('Ce paquet n’est pas disponible.');if(copy.length+9>200)throw Error('200 pièces maximum : regroupe quelques paquets avant de décomposer.');copy.splice(i,1,...Array(10).fill(value/10));}else {if(copy.filter(v=>v===value/10).length<10)throw Error('Il faut dix petits paquets pour faire cet échange.');for(let n=0;n<10;n++)copy.splice(copy.indexOf(value/10),1);copy.push(value);}return copy.sort((a,b)=>b-a);
 }
 function toolsHtml(q){if(q.track==='doom')return '';return `${prefs.table?`<details class="learning-tool"><summary>Tableau de numération</summary><div id="place-table-content">${tableHtml(q)}</div></details>`:''}${prefs.blocks?`<details class="learning-tool"><summary>Manipuler les quantités</summary><p>Choisis un entier de 0 à 9 999. Clique les pièces pour les compter. Les échanges gardent la même quantité.</p><form id="blocks-form" class="formrow"><label>Nombre à représenter<input id="blocks-number" type="number" min="0" max="9999" step="1" value="${Number.isInteger(q.a)&&q.a<=9999?q.a:0}" required inputmode="numeric"></label><button>Afficher les pièces</button></form><p class="muted">Une unité vaut 1, une barre 10, une plaque 100 et un cube 1 000. Pour les décimales, utilise le tableau de numération.</p><div id="blocks-pieces" class="blocks-pieces"></div><p id="blocks-count" role="status"></p><div class="blocks-exchange"><label>Paquet à échanger<select id="blocks-value"><option value="10">Une dizaine</option><option value="100">Une centaine</option><option value="1000">Un millier</option></select></label><button id="blocks-split" type="button">Décomposer en 10 pièces</button><button id="blocks-group" type="button">Regrouper 10 pièces</button></div><p id="blocks-feedback" role="status"></p></details>`:''}`;}
 function bindTools(container,q){
  const query=s=>container.querySelector(s);if(!query('#blocks-form'))return;let list=pieces(Number(query('#blocks-number').value)),selected=new Set();
  const names={1:'une unité',10:'une dizaine',100:'une centaine',1000:'un millier'};
  const count=()=>{const total=[...selected].reduce((n,i)=>n+list[i],0);query('#blocks-count').textContent=`Pièces sélectionnées : ${fmt(total)}. Quantité représentée : ${fmt(list.reduce((a,b)=>a+b,0))}.`;};
  function draw(){query('#blocks-pieces').innerHTML=list.map((v,i)=>`<button type="button" class="base-block block-${v}" data-piece="${i}" aria-label="Sélectionner ${names[v]}, valeur ${v}" aria-pressed="false"><span class="block-shape" aria-hidden="true"></span><span>${fmt(v)}</span></button>`).join('')||'<p>Aucune pièce : le nombre est zéro.</p>';selected.clear();query('#blocks-pieces').querySelectorAll('[data-piece]').forEach(button=>button.onclick=()=>{const i=Number(button.dataset.piece);if(selected.has(i))selected.delete(i);else selected.add(i);button.setAttribute('aria-pressed',selected.has(i));count();});count();}
  query('#blocks-form').onsubmit=event=>{event.preventDefault();try{list=pieces(Number(query('#blocks-number').value));draw();query('#blocks-feedback').textContent='';}catch(e){query('#blocks-feedback').textContent=e.message;}};
  for(const direction of ['split','group'])query('#blocks-'+direction).onclick=()=>{try{list=exchange(list,Number(query('#blocks-value').value),direction);draw();query('#blocks-feedback').textContent='Échange effectué : la quantité est conservée.';}catch(e){query('#blocks-feedback').textContent=e.message;}};
  draw();
 }
 function correctionHtml(q,index=0){const steps=correction(q),i=Math.min(index,steps.length-1);return `<section class="step-correction" aria-label="Correction par étapes"><h3>Comprenons le calcul</h3><p class="hint">Étape ${i+1} sur ${steps.length}</p><p id="correction-text" role="status" tabindex="-1">${root.NumberDisplay?root.NumberDisplay.html(steps[i].text):escape(steps[i].text)}</p><div class="actions"><button id="correction-prev" type="button" ${i===0?'disabled':''}>Étape précédente</button><button id="correction-next" type="button" ${i===steps.length-1?'disabled':''}>Étape suivante</button></div>${i===steps.length-1?'<p>Tu peux relire les étapes ou passer à la question suivante.</p>':''}</section>`;}
 const api={defaults,clean,set,autoNext,configure,apply,settingsHtml,bindSettings,parts,correction,digits,tableHtml,pieces,exchange,toolsHtml,bindTools,correctionHtml,get prefs(){return {...prefs};}};
 if(typeof module==='object'&&module.exports)module.exports=api;else root.MathLearning=api;
})(globalThis);
